# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 157ba52312678524ec714fac976ee6d3e9615b987a3df555b6958dd08bd77d7552105011ad369bb8c620e2d4b84012ca434e5cb96d600ef21c27c41161805b07

test:
  secret_key_base: 6581ce7ab06a65a28e768707c7c3b3e1b04e1d93f43bafdd5d9cad9184712503578c123b04539a7e96b053ae04cfc150782cec63e28a3696a92370f28040b105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
